#region Copyright & License Information
/*
 * Copyright (c) The OpenRA Developers and Contributors
 * This file is part of OpenRA, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see COPYING.
 */
#endregion

// This file is generated by OpenRA.Browser/tests/strategy-catalog-gate.mjs.
// Run `node tests/strategy-catalog-gate.mjs --write-generated` from OpenRA.Browser.

using System;
using System.Collections.Generic;

namespace OpenRA.Browser
{
	static class AgentStrategyCatalog
	{
		internal const int SchemaVersion = 1;
		internal const int CatalogVersion = 1;
		internal const string CatalogFileHash = "12b18a77178e2ff9cedc6ffa79f0d2d89e43decf33bba632f3b2de6dff3acf94";
		internal const string ManualFileHash = "b2d998eefb72bf1feb40c0c5bf386f99cd033e1fb4149089d3fae9b964fcdfe1";
		internal const string RulesGraphHash = "a09c075878bef51d2c1e4c3364d0e2673452d843ec9b50fa4e71c48d93cc8921";
		internal const string RulesArtifactHash = "f1549b9a9147415fb9260cac031c5a58c6ad57d09a95a06cccddf7462fd8178e";
		internal const string RulesHash = "b4b516bdc4397ac93245ae59dc43fe598a885ebc22a4dce1cb9fc94155ed6222";

		internal sealed class Entry
		{
			internal string Id { get; }
			internal int Version { get; }
			internal string Faction { get; }
			internal string[] Requirements { get; }

			internal Entry(string id, int version, string faction, string[] requirements)
			{
				Id = id;
				Version = version;
				Faction = faction;
				Requirements = requirements;
			}
		}

		internal static readonly IReadOnlyDictionary<string, Entry> Entries =
			new Dictionary<string, Entry>(StringComparer.Ordinal)
			{
				["allied-e3-mass"] = new("allied-e3-mass", 2, "allies", ["landRoute"]),
				["allied-fast-boom"] = new("allied-fast-boom", 2, "allies", []),
				["soviet-grenadier-rush"] = new("soviet-grenadier-rush", 2, "soviets", ["landRoute"]),
				["soviet-tank-pressure"] = new("soviet-tank-pressure", 2, "soviets", ["landRoute"]),
			};

		internal static IReadOnlyList<string> StrategyIds { get; } =
		[
			"allied-e3-mass",
			"allied-fast-boom",
			"soviet-grenadier-rush",
			"soviet-tank-pressure",
		];
	}
}
