mod-title = STEELSEED
faction-foundry = Foundry
faction-lattice = Lattice
faction-random = Random
bot-name = Sentry
actor-foundry-rivet-name = Rivet
actor-foundry-clamp-name = Clamp
actor-foundry-cinder-name = Cinder
actor-foundry-warden-name = Warden
actor-foundry-tread-name = Tread
actor-foundry-rammer-name = Rammer
actor-foundry-anvil-name = Anvil
actor-foundry-kiln-name = Kiln
actor-foundry-rack-name = Rack
actor-foundry-dragline-name = Dragline
actor-foundry-bellows-name = Bellows
actor-foundry-flywheel-name = Flywheel
actor-lattice-shard-name = Shard
actor-lattice-prism-name = Prism
actor-lattice-weaver-name = Weaver
actor-lattice-chorus-name = Chorus
actor-lattice-skimmer-name = Skimmer
actor-lattice-kite-name = Kite
actor-lattice-stilt-name = Stilt
actor-lattice-aperture-name = Aperture
actor-lattice-cantilever-name = Cantilever
actor-lattice-phase-name = Phase
actor-lattice-vesper-name = Vesper
actor-lattice-helix-name = Helix
actor-foundry-crucible-name = Crucible
actor-foundry-rivetworks-name = Rivetworks
actor-foundry-trackyard-name = Trackyard
actor-foundry-skyhook-name = Skyhook
actor-foundry-boiler-name = Boiler
actor-foundry-store-name = Store
actor-foundry-bulwark-name = Bulwark
actor-foundry-flakrack-name = Flak Rack
actor-foundry-forge-name = Forge
actor-foundry-relay-name = Relay
actor-lattice-nexus-name = Nexus
actor-lattice-extruder-name = Extruder
actor-lattice-frameyard-name = Frameyard
actor-lattice-aerie-name = Aerie
actor-lattice-cell-name = Cell
actor-lattice-reservoir-name = Reservoir
actor-lattice-pylon-name = Pylon
actor-lattice-prong-name = Prong
actor-lattice-mandala-name = Mandala
actor-lattice-lens-name = Lens
checkbox-developer-mode =
    .label = Development controls
    .description = Enable local simulation diagnostics.
notification-cheat-disabled = { $player } disabled { $cheat }.
notification-cheat-enabled = { $player } enabled { $cheat }.
notification-cheat-used = { $player } used { $cheat }{ $suffix }.
label-tooltip-prefix =
    .ally = Allied
    .enemy = Hostile
tileset-steelworks = Steelworks
map-generator-seedline = Seedline
map-title-seedline = Seedline Skirmish
map-generator-option-preset = Battlefield
map-preset-amber-crossing =
    .label = Amber Crossing
map-preset-cyan-fold =
    .label = Cyan Fold
map-preset-ceramic-quadrant =
    .label = Ceramic Quadrant
map-preset-foundry-cross =
    .label = Foundry Cross
options-game-speed-default = Standard
checkbox-separate-spawns = Separate team starts
checkbox-separate-spawns-description = Keep friendly command forces near one another.
checkbox-short-game = Short engagement
checkbox-short-game-description = Defeat follows when all required command forces are destroyed.
dropdown-tech-level = Technology
dropdown-tech-level-description = Select the available technology level.
dropdown-game-speed = Simulation speed
dropdown-game-speed-description = Select the simulation tick rate.
checkbox-fog = Sensor fog
checkbox-fog-description = Hide terrain outside sensor coverage.
checkbox-explored = Surveyed terrain
checkbox-explored-description = Begin with the terrain grid surveyed.
enumerated-bot-name = { $name } { $number }
notification-chat-temp-disabled = Chat is disabled for { $remaining } seconds.
notification-custom-rules = This match uses custom rules.
notification-desync-compare-logs = Synchronization diverged at frame { $frame }.
notification-error-game-started = The match has already started.
notification-game-full = The match is full.
notification-game-has-started = The match has started.
notification-game-paused = { $player } paused the match.
notification-game-started = The match has started.
notification-game-unpaused = { $player } resumed the match.
notification-incompatible-mod = This mod is incompatible.
notification-incompatible-protocol = The network protocol is incompatible.
notification-incompatible-version = The version is incompatible.
notification-incorrect-password = The password is incorrect.
notification-insufficient-votes-to-kick = There are not enough votes to remove { $kickee }.
notification-joined = { $player } joined.
notification-kick-already-voted = A vote is already in progress.
notification-lobby-disconnected = { $player } left the lobby.
notification-new-admin = { $player } is now the administrator.
notification-no-permission-to-join = Permission to join was denied.
notification-observer-disconnected = Observer { $player } disconnected.
notification-player-disconnected = { $player } disconnected.
notification-requires-authentication = Authentication is required.
notification-requires-password = A password is required.
notification-saved-screenshot = Screenshot saved to { $filename }.
notification-team-player-disconnected = { $player } from team { $team } disconnected.
notification-two-humans-required = Two human players are required.
notification-unable-to-start-a-vote = The vote could not be started.
notification-unknown-server-command = Unknown command: { $command }.
notification-vote-kick-ended = The vote concerning { $kickee } ended.
notification-vote-kick-in-progress = Vote concerning { $kickee }: { $percentage } percent.
notification-vote-kick-started = { $kicker } started a vote concerning { $kickee }.
notification-you-were-banned = You were banned.
notification-you-were-kicked = You were removed from the match.
notification-you-were-temp-banned = You were temporarily banned.
notification-player-is-victorious = { $player } is victorious.
notification-player-is-defeated = { $player } is defeated.
notification-admin-change-configuration = Only the administrator can change the match configuration.
notification-admin-change-map = Only the administrator can change the battlefield.
notification-admin-clear-spawn = Only the administrator can clear a start position.
notification-admin-kick = Only the administrator can remove a player.
notification-admin-kicked = { $admin } removed { $player }.
notification-admin-lobby-info = Only the administrator can update the lobby.
notification-admin-move-spectators = Only the administrator can move spectators.
notification-admin-option = Only the administrator can change match options.
notification-admin-start-game = Only the administrator can start the match.
notification-admin-transfer-admin = Only the administrator can transfer control.
notification-changed-map = { $player } selected battlefield { $map }.
notification-empty-slot = That player slot is empty.
notification-error-number-teams = Team count { $raw } is invalid.
notification-insufficient-enabled-spawn-points = Not enough start positions are enabled.
notification-invalid-bot-slot = The selected bot slot is invalid.
notification-invalid-bot-type = The selected bot type is invalid.
notification-invalid-configuration-command = The match configuration command is invalid.
notification-invalid-faction-selected = Faction { $faction } is invalid.
notification-invalid-lobby-info = The lobby configuration is invalid.
notification-invalid-player-color = The selected command color is unavailable.
notification-kick-none = No matching player was found.
notification-kick-self = The administrator cannot remove themselves.
notification-kicked = { $player } was removed.
notification-malformed-command = Command { $command } is malformed.
notification-map-bots-disabled = Bots are disabled on this battlefield.
notification-move-spectators = { $admin } moved { $player } to spectators.
notification-nick-changed = { $player } is now known as { $name }.
notification-no-kick-game-started = Players cannot be removed after the match starts.
notification-no-start-until-required-slots-full = Required player slots must be filled before starting.
notification-no-start-without-players = At least one player is required.
notification-player-color-player = That command color is too close to another force.
notification-player-color-terrain = That command color is too close to the terrain.
notification-requires-host = This command requires the match host.
notification-searching-map = Resolving the generated battlefield.
notification-slot-closed = That player slot is closed.
notification-spawn-locked = That start position is locked.
notification-spawn-occupied = That start position is occupied.
notification-state-unchanged-game-started = Command { $command } cannot change state after the match starts.
notification-state-unchanged-ready = The player is already ready.
notification-temp-ban = { $admin } temporarily removed { $player }.
notification-unknown-map = The generated battlefield is unavailable.
notification-vote-kick-disabled = Player removal votes are disabled.

actor-foundry-bastion-name = Bastion
actor-foundry-grapnel-name = Grapnel
actor-foundry-capstan-name = Capstan
actor-foundry-hawser-name = Hawser
actor-lattice-meridian-name = Meridian
actor-lattice-skiff-name = Skiff
actor-lattice-caisson-name = Caisson
actor-lattice-halyard-name = Halyard
actor-foundry-slipway-name = Slipway
actor-lattice-quay-name = Quay

actor-foundry-bolt-name = Bolt
actor-foundry-ember-name = Ember
actor-foundry-flint-name = Flint
actor-foundry-ingot-name = Ingot
actor-lattice-cipher-name = Cipher
actor-lattice-filament-name = Filament
actor-lattice-quill-name = Quill
actor-lattice-vector-name = Vector
actor-foundry-hammer-name = Hammer
actor-foundry-mandrel-name = Mandrel
actor-foundry-tongs-name = Tongs
actor-foundry-bollard-name = Bollard
actor-foundry-girder-name = Girder
actor-foundry-cleat-name = Cleat
actor-lattice-apex-name = Apex
actor-lattice-chord-name = Chord
actor-lattice-facet-name = Facet
actor-lattice-node-name = Node
actor-lattice-spire-name = Spire
actor-lattice-truss-name = Truss
actor-foundry-gale-name = Gale
actor-foundry-thermal-name = Thermal
actor-foundry-updraft-name = Updraft
actor-lattice-zephyr-name = Zephyr
actor-lattice-cirrus-name = Cirrus
actor-lattice-spectra-name = Spectra
actor-foundry-redoubt-name = Redoubt
actor-foundry-ravelin-name = Ravelin
actor-foundry-casemate-name = Casemate
actor-lattice-trellis-name = Trellis
actor-lattice-obelisk-name = Obelisk
actor-lattice-beacon-name = Beacon
actor-foundry-dredger-name = Dredger
actor-foundry-tender-name = Tender
actor-lattice-pontoon-name = Pontoon
actor-foundry-retort-name = Retort
actor-foundry-cupola-name = Cupola
actor-foundry-tapping-name = Tapping
actor-foundry-hearth-name = Hearth
actor-lattice-array-name = Array
actor-lattice-plenum-name = Plenum
actor-lattice-spindle-name = Spindle
actor-lattice-vault-name = Vault
